AWSTemplateFormatVersion: '2010-09-09'
Description: craft-sync

Resources:
  CraftSyncInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-01c647eace872fc02
      KeyName: craft-sync
      SecurityGroupIds:
        - !Ref CraftSyncSecurityGroup

  CraftSyncSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH and WebSocket ports
      VpcId: vpc-0fece7d891bcedf57
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref CraftSyncInstance

  PublicIP:
    Description: The public IP of the EC2 instance
    Value: !GetAtt CraftSyncInstance.PublicIp
