AWSTemplateFormatVersion: '2010-09-09'
Description: craft-sync

Resources:
  CraftSyncInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-01c647eace872fc02
      KeyName: craft-sync
      SecurityGroupIds:
        - !Ref CraftSyncSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum update -y
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            . ~/.nvm/nvm.sh
            nvm install node
            aws s3 cp s3://craft-sync-deployment/craft-sync.tar.gz /home/ec2-user/
            mkdir craft-sync
            tar -xzvf /home/ec2-user/craft-sync.tar.gz -C /home/ec2-user/craft-sync
            cd /home/ec2-user/craft-sync
            npm install
            nohup node main.js > /dev/null 2>&1 &

  CraftSyncSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH and WebSocket ports
      VpcId: vpc-0fece7d891bcedf57
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref CraftSyncInstance

  PublicIP:
    Description: The public IP of the EC2 instance
    Value: !GetAtt CraftSyncInstance.PublicIp
